%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from conf.d config subdir
  # - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

llsfrb:
  sps:
    enable: false
    host: !ipv4 192.168.1.77
    port: !tcp-port 502

  clips:
    # Timer interval, in milliseconds
    timer-interval: 40

  comm:
    server-port: !tcp-port 4444
    peer-host: !ipv4 192.168.0.255
    peer-port: !udp-port 4444
    
