%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from conf.d config subdir
  # - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

llsfrb:
  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  sps:
    enable: true
    host: !ipv4 192.168.1.77
    port: !tcp-port 502
    test-lights: true

  clips:
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, rfid-input, signal, gamestate]
    unwatch-rules: [retract-time, rfid-input-cleanup, net-send-beacon, update-gametime-points,
                    update-last-time, net-send-GameState, net-send-OrderInfo,
                    net-send-MachineInfo, net-send-PuckInfo, net-send-RobotInfo,
                    exploration-send-MachineReportInfo, net-broadcast-MachineInfo,
                    net-send-VersionInfo]

  comm:
    protobuf-dirs: ["@BASEDIR@/src/msgs"]
    server-port: !tcp-port 4444
    peer-host: !ipv4 172.26.255.255
    peer-port: !udp-port 4444
    #peer-send-port: !udp-port 4444
    #peer-recv-port: !udp-port 4445
    

  game:
    teams: [Carologistics]
